kat, Makefile, .gitignore, tests/output: log failing tests as well

diff --git a/kat b/kat
--- a/kat
+++ b/kat
@@ -2,6 +2,15 @@
 
 set -e      # Exit immediately if any command fails
 
+build_dir="$(pwd)/.build"
+test_logs="$build_dir/logs"
+failing_log="$test_logs/failing.lastrun"
+mkdir -p "$test_logs"
+
+test_expected_dir="tests/output"
+test_output_dir="$test_logs/output"
+mkdir -p "$test_expected_dir" "$test_output_dir"
+
 # Utilities
 # ---------
 
@@ -16,7 +25,6 @@ pretty_diff() {
 # -----------------
 
 run_env() {
-    local build_dir="$(pwd)/.build"
     local release_dir="$build_dir/k/k-distribution/target/release/k"
     export PATH="$release_dir/lib/native/linux:$release_dir/lib/native/linux64:$release_dir/bin/:$PATH"
 }
@@ -49,15 +57,14 @@ run_ksearch() {
 }
 
 run_test() {
-    local imp_file strategy_file test_number counter output_dir output_prefix exit_status
+    local imp_file strategy_file test_number counter exit_status current_status
+    local test_id test_output_file test_expected_file
     imp_file="$1"      ; shift
     strategy_file="$1" ; shift
     { test_number="$1" && shift ; } || test_number="*"
-    output_dir="tests/output"
 
     [[ -f "$imp_file"      ]] || die "File '$imp_file' does not exist ..."
     [[ -f "$strategy_file" ]] || die "File '$strategy_file' does not exist ..."
-    mkdir -p "$output_dir"
 
     exit_status=0
     counter=0
@@ -66,13 +73,23 @@ run_test() {
         counter=$((counter + 1))
         [[ "$test_number" == '*' ]] || [[ "$test_number" == "$counter" ]] || continue
 
-        output_prefix="$output_dir/$(echo $(basename $imp_file) $strategy | md5sum | cut --delimiter=' ' --field=1)"
-        progress "testing: '$imp_file' with strategy '$strategy', output to $output_prefix.out"
-        echo "Program:  $imp_file"           > "$output_prefix.out"
-        echo "Strategy: $strategy"          >> "$output_prefix.out"
-        { printf '=%.0s' {1..80} ; echo ; } >> "$output_prefix.out"
-        run_krun "$imp_file" "$strategy"    >> "$output_prefix.out"
-        pretty_diff "$output_prefix.expected" "$output_prefix.out" || exit_status="$?"
+        test_id="$(echo $(basename $imp_file) $strategy | md5sum | cut --delimiter=' ' --field=1)"
+        test_output_file="$test_output_dir/$test_id.out"
+        test_expected_file="$test_expected_dir/$test_id.out"
+        progress "testing: '$imp_file' with strategy '$strategy', expected output $test_expected_file"
+        [[ -f "$test_expected_file" ]] || die "Expected output file does not exist: $test_expected_file"
+
+        echo "Program:  $imp_file"           > "$test_output_file"
+        echo "Strategy: $strategy"          >> "$test_output_file"
+        { printf '=%.0s' {1..80} ; echo ; } >> "$test_output_file"
+        run_krun "$imp_file" "$strategy"    >> "$test_output_file"
+
+        current_status='0'
+        pretty_diff "$test_expected_file" "$test_output_file" || current_status="$?"
+        if [[ "$current_status" != '0' ]]; then
+            echo "$imp_file with strategy '$strategy'" >> "$failing_log"
+            exit_status="$current_status"
+        fi
     done < "$strategy_file"
     return "$exit_status"
 }
